version: 2.1

commands:
  destroy-environment:
    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
    parameters:
      # Add parameter here   
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
            # Your code here
            exit 1

  revert-migrations:
    description: Revert the last migration if successfully run in the current workflow.
    parameters:
      # Add parameter here     
    steps:
      - run:
          name: Revert migrations
          # Add when this will run
          command: |
            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
            SUCCESS = 1
            if(( $SUCCESS==1 )); 
            then
            #  cd ~/project/backend
            #  npm install
            #  Add revert code here. You can find this in the Getting Started section.
              exit 1
            fi
            
           
  jobs:
    build-frontend:
      docker:
      # Step 1.1 Select a Docker image that is compatible with NodeJS
        - image: cimg/node:13.8.0    
  
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            # Step 1.2 - Your code here
            # Add code to build/compile the front-end
            cd frontend
            npm install
            npm run build
            # exit 1
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

    build-backend:
      docker:
        # Step 1.3 Select a Docker image that is compatible with NodeJS
        - image: cimg/node:13.8.0
      steps:
        - checkout
        - restore_cache:
            keys: [backend-build]
        - run:
            name: Back-end build
            command: |
              # Step 1.4 - Your code here
              # Add code to build/compile the back-end
              cd backend
              npm install
              npm run build
              # exit 1
        - save_cache:
            paths: [backend/node_modules]
            key: backend-build

# 
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
